BINARY_NAME=tjoApp

build:
	@echo "Building Tjo..."
	@go build -o tmp/${BINARY_NAME} .
	@npm install
	@npm run build
	@echo "Tjo built!"

run: build start_compose
	@echo "Starting Tjo..."
	@./tmp/${BINARY_NAME} &
	@npm run watch
	@echo "Tjo started!"

clean:
	@echo "Cleaning..."
	@go clean
	@rm tmp/${BINARY_NAME}
	@echo "Cleaned!"

start_compose:
	docker-compose up -d

stop_compose:
	docker-compose down

test:
	@echo "Testing..."
	@go test ./...
	@echo "Done!"

start: run

dev: run

stop:
	@echo "Stopping Tjo..."
	@-pkill -SIGTERM -f "./tmp/${BINARY_NAME}"
	@echo "Stopped Tjo!"

restart: stop start
