BINARY_NAME=gemquickApp.exe

build:
	@echo "Building Gemquick..."
	@go build -o tmp/${BINARY_NAME} .
	@npx tailwindcss -i ./resources/css/styles.css -o ./public/css/styles.css
	@echo "Gemquick built!"

run: build start_compose
	@echo "Starting Gemquick..."
	@start /min cmd /c tmp\${BINARY_NAME} &
	@npx tailwindcss -i ./resources/css/styles.css -o ./public/css/styles.css --watch
	@echo "Gemquick started!"

clean:
	@echo "Cleaning..."
	@DEL ${BINARY_NAME}
	@go clean
	@echo "Cleaned!"

start_compose:
	docker-compose up -d

stop_compose:
	docker-compose down

test:
	@echo "Testing..."
	@go test ./...
	@echo "Done!"

start: run

dev: run

stop:
	@echo "Stopping Gemquick..."
	@taskkill /IM ${BINARY_NAME} /F"
	@echo "Stopped Gemquick!"

restart: stop start